version: "3.9"
services:
  # client
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: sh -c "yarn dev"
  # server
  server:
    build: ./server
    env_file:
      - ./server/.env.dev
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server/:/app/
    depends_on:
    - db
    - redis
 # database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env.dev.db
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev.db

  celery:
    build: ./server
    command: "celery -A server worker -l INFO -E"

    depends_on:
      - server
    env_file:
      - ./server/.env.dev

  celery-beats:
    build: ./server
    command: "celery -A server beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - server
      - celery
    env_file:
      - ./server/.env.dev

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379